/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MultiProjectKanbanPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/KanbanBoardView.ts
var import_obsidian2 = require("obsidian");

// src/dataManager.ts
var import_obsidian = require("obsidian");

// src/utils.ts
function generateId(prefix) {
  return `${prefix}-${Date.now()}${Math.floor(Math.random() * 1e3)}`;
}
function findCardLocation(data, cardId) {
  for (const project of data.projects) {
    for (const column of project.columns) {
      const cardIndex = column.cards.findIndex((c) => c.id === cardId);
      if (cardIndex !== -1) {
        return { project, column, cardIndex };
      }
    }
  }
  return void 0;
}
function findColumnLocation(data, columnId) {
  for (const project of data.projects) {
    const columnIndex = project.columns.findIndex((c) => c.id === columnId);
    if (columnIndex !== -1) {
      return { project, columnIndex };
    }
  }
  return void 0;
}

// src/dataManager.ts
var FRONTMATTER_REGEX = /^---\n([\s\S]*?)\n---/;
var DONE_COLUMN_NAME = "Done";
function isDoneColumn(column) {
  return column.name === DONE_COLUMN_NAME;
}
function ensureDoneColumns(data) {
  let changed = false;
  const projects = data.projects.map((p) => {
    const hasDone = p.columns.some((c) => isDoneColumn(c));
    if (hasDone)
      return p;
    changed = true;
    return {
      ...p,
      columns: [...p.columns, { id: generateId("col"), name: DONE_COLUMN_NAME, cards: [] }]
    };
  });
  return changed ? { ...data, projects } : data;
}
function parseBoardData(fileContent) {
  const match = fileContent.match(FRONTMATTER_REGEX);
  if (!match)
    return null;
  try {
    const yaml = (0, import_obsidian.parseYaml)(match[1]);
    if (!yaml || yaml["kanban-board"] !== true)
      return null;
    const data = {
      "kanban-board": true,
      projects: []
    };
    if (Array.isArray(yaml.projects)) {
      data.projects = yaml.projects.map((p) => ({
        id: p.id || generateId("proj"),
        name: p.name || "Untitled Project",
        color: p.color || "#4a90d9",
        collapsed: p.collapsed === true,
        columns: Array.isArray(p.columns) ? p.columns.map((c) => ({
          id: c.id || generateId("col"),
          name: c.name || "Untitled Column",
          cards: Array.isArray(c.cards) ? c.cards.map((card) => ({
            id: card.id || generateId("card"),
            title: card.title || ""
          })) : []
        })) : []
      }));
    }
    return data;
  } catch (e) {
    return null;
  }
}
function serializeBoardData(data) {
  const yaml = (0, import_obsidian.stringifyYaml)(data);
  return `---
${yaml}---
`;
}
function createEmptyBoardData() {
  return {
    "kanban-board": true,
    projects: []
  };
}
function addProject(data, name) {
  const project = {
    id: generateId("proj"),
    name,
    color: "#4a90d9",
    collapsed: false,
    columns: [{ id: generateId("col"), name: DONE_COLUMN_NAME, cards: [] }]
  };
  return {
    ...data,
    projects: [...data.projects, project]
  };
}
function removeProject(data, projectId) {
  return {
    ...data,
    projects: data.projects.filter((p) => p.id !== projectId)
  };
}
function updateProject(data, projectId, updates) {
  return {
    ...data,
    projects: data.projects.map(
      (p) => p.id === projectId ? { ...p, ...updates } : p
    )
  };
}
function addColumn(data, projectId, name) {
  const column = {
    id: generateId("col"),
    name,
    cards: []
  };
  return {
    ...data,
    projects: data.projects.map((p) => {
      if (p.id !== projectId)
        return p;
      const doneIndex = p.columns.findIndex((c) => isDoneColumn(c));
      if (doneIndex === -1) {
        return { ...p, columns: [...p.columns, column] };
      }
      const newColumns = [...p.columns];
      newColumns.splice(doneIndex, 0, column);
      return { ...p, columns: newColumns };
    })
  };
}
function removeColumn(data, projectId, columnId) {
  const project = data.projects.find((p) => p.id === projectId);
  const column = project == null ? void 0 : project.columns.find((c) => c.id === columnId);
  if (column && isDoneColumn(column))
    return data;
  return {
    ...data,
    projects: data.projects.map(
      (p) => p.id === projectId ? { ...p, columns: p.columns.filter((c) => c.id !== columnId) } : p
    )
  };
}
function updateColumn(data, projectId, columnId, updates) {
  const project = data.projects.find((p) => p.id === projectId);
  const column = project == null ? void 0 : project.columns.find((c) => c.id === columnId);
  if (column && isDoneColumn(column))
    return data;
  return {
    ...data,
    projects: data.projects.map(
      (p) => p.id === projectId ? {
        ...p,
        columns: p.columns.map(
          (c) => c.id === columnId ? { ...c, ...updates } : c
        )
      } : p
    )
  };
}
function addCard(data, projectId, columnId, title) {
  const card = {
    id: generateId("card"),
    title
  };
  return {
    ...data,
    projects: data.projects.map(
      (p) => p.id === projectId ? {
        ...p,
        columns: p.columns.map(
          (c) => c.id === columnId ? { ...c, cards: [...c.cards, card] } : c
        )
      } : p
    )
  };
}
function removeCard(data, cardId) {
  return {
    ...data,
    projects: data.projects.map((p) => ({
      ...p,
      columns: p.columns.map((c) => ({
        ...c,
        cards: c.cards.filter((card) => card.id !== cardId)
      }))
    }))
  };
}
function updateCard(data, cardId, updates) {
  return {
    ...data,
    projects: data.projects.map((p) => ({
      ...p,
      columns: p.columns.map((c) => ({
        ...c,
        cards: c.cards.map(
          (card) => card.id === cardId ? { ...card, ...updates } : card
        )
      }))
    }))
  };
}
function moveCard(data, cardId, targetProjectId, targetColumnId, targetIndex) {
  const location = findCardLocation(data, cardId);
  if (!location)
    return data;
  const card = location.column.cards[location.cardIndex];
  let newData = {
    ...data,
    projects: data.projects.map((p) => ({
      ...p,
      columns: p.columns.map((c) => ({
        ...c,
        cards: c.cards.filter((cd) => cd.id !== cardId)
      }))
    }))
  };
  newData = {
    ...newData,
    projects: newData.projects.map(
      (p) => p.id === targetProjectId ? {
        ...p,
        columns: p.columns.map((c) => {
          if (c.id !== targetColumnId)
            return c;
          const newCards = [...c.cards];
          const insertAt = Math.min(targetIndex, newCards.length);
          newCards.splice(insertAt, 0, card);
          return { ...c, cards: newCards };
        })
      } : p
    )
  };
  return newData;
}
function moveColumn(data, columnId, targetProjectId, targetIndex) {
  const location = findColumnLocation(data, columnId);
  if (!location)
    return data;
  if (location.project.id !== targetProjectId)
    return data;
  const column = location.project.columns[location.columnIndex];
  if (isDoneColumn(column))
    return data;
  return {
    ...data,
    projects: data.projects.map((p) => {
      if (p.id !== targetProjectId)
        return p;
      const newColumns = p.columns.filter((c) => c.id !== columnId);
      const doneIndex = newColumns.findIndex((c) => isDoneColumn(c));
      const maxIndex = doneIndex !== -1 ? doneIndex : newColumns.length;
      const insertAt = Math.min(targetIndex, maxIndex);
      newColumns.splice(insertAt, 0, column);
      return { ...p, columns: newColumns };
    })
  };
}

// src/dragDrop.ts
var COLUMN_MIME = "application/kanban-column";
var activeColumnDrag = null;
function isColumnDragActive() {
  return activeColumnDrag !== null;
}
function resetColumnDragState() {
  activeColumnDrag = null;
  document.querySelectorAll(".kanban-column-placeholder").forEach((el) => el.remove());
  document.querySelectorAll(".dragging-column").forEach((el) => el.removeClass("dragging-column"));
}
function setupCardDrag(cardEl, cardId, projectId, columnId) {
  cardEl.draggable = true;
  cardEl.addEventListener("dragstart", (e) => {
    if (isColumnDragActive()) {
      e.preventDefault();
      return;
    }
    if (!e.dataTransfer)
      return;
    e.dataTransfer.setData("application/kanban-card", JSON.stringify({
      cardId,
      sourceProjectId: projectId,
      sourceColumnId: columnId
    }));
    e.dataTransfer.effectAllowed = "move";
    cardEl.addClass("dragging");
  });
  cardEl.addEventListener("dragend", () => {
    cardEl.removeClass("dragging");
    document.querySelectorAll(".kanban-placeholder").forEach((el) => el.remove());
  });
}
function setupColumnDrag(gripEl, columnEl, projectId, columnId) {
  gripEl.draggable = true;
  gripEl.addEventListener("dragstart", (e) => {
    if (!e.dataTransfer)
      return;
    e.dataTransfer.setData(COLUMN_MIME, columnId);
    e.dataTransfer.effectAllowed = "move";
    activeColumnDrag = { columnId, sourceProjectId: projectId };
    requestAnimationFrame(() => {
      columnEl.addClass("dragging-column");
    });
  });
  gripEl.addEventListener("dragend", () => {
    resetColumnDragState();
  });
}
function setupColumnDropZone(columnsContainer, projectId, callbacks) {
  columnsContainer.addEventListener("dragover", (e) => {
    if (!activeColumnDrag)
      return;
    e.preventDefault();
    if (e.dataTransfer)
      e.dataTransfer.dropEffect = "move";
  }, true);
  columnsContainer.addEventListener("drop", (e) => {
    if (!activeColumnDrag)
      return;
    e.preventDefault();
  }, true);
  columnsContainer.addEventListener("dragover", (e) => {
    if (!activeColumnDrag)
      return;
    e.preventDefault();
    columnsContainer.querySelectorAll(".kanban-column-placeholder").forEach((el) => el.remove());
    const afterColumn = getDragAfterColumn(columnsContainer, e.clientX);
    const placeholder = createDiv({ cls: "kanban-column-placeholder" });
    if (afterColumn) {
      columnsContainer.insertBefore(placeholder, afterColumn);
    } else {
      const addColBtn = columnsContainer.querySelector(".kanban-add-column");
      if (addColBtn) {
        columnsContainer.insertBefore(placeholder, addColBtn);
      } else {
        columnsContainer.appendChild(placeholder);
      }
    }
  });
  columnsContainer.addEventListener("dragleave", (e) => {
    if (!activeColumnDrag)
      return;
    if (!columnsContainer.contains(e.relatedTarget)) {
      columnsContainer.querySelectorAll(".kanban-column-placeholder").forEach((el) => el.remove());
    }
  });
  columnsContainer.addEventListener("drop", (e) => {
    if (!activeColumnDrag)
      return;
    e.preventDefault();
    e.stopPropagation();
    columnsContainer.querySelectorAll(".kanban-column-placeholder").forEach((el) => el.remove());
    const payload = activeColumnDrag;
    activeColumnDrag = null;
    if (payload.sourceProjectId !== projectId)
      return;
    const afterColumn = getDragAfterColumn(columnsContainer, e.clientX);
    const allColumns = Array.from(
      columnsContainer.querySelectorAll(".kanban-column:not(.dragging-column)")
    );
    let targetIndex;
    if (afterColumn) {
      targetIndex = allColumns.indexOf(afterColumn);
    } else {
      targetIndex = allColumns.length;
    }
    const data = callbacks.getData();
    const newData = moveColumn(data, payload.columnId, projectId, targetIndex);
    callbacks.onDataChanged(newData);
  });
}
function getDragAfterColumn(container, x) {
  const columns = Array.from(
    container.querySelectorAll(".kanban-column:not(.dragging-column)")
  );
  let closest = null;
  let closestOffset = Number.POSITIVE_INFINITY;
  for (const col of columns) {
    const box = col.getBoundingClientRect();
    const midX = box.left + box.width / 2;
    const offset = midX - x;
    if (offset > 0 && offset < closestOffset) {
      closestOffset = offset;
      closest = col;
    }
  }
  return closest;
}

// src/renderer.ts
function renderBoard(container, callbacks) {
  const data = callbacks.getData();
  const boardEl = container.createDiv({ cls: "kanban-board" });
  const addProjectBtn = boardEl.createEl("button", {
    cls: "kanban-add-project-btn",
    text: "Add Project"
  });
  addProjectBtn.addEventListener("click", () => {
    startInlineInput(addProjectBtn, "Project name...", (name) => {
      if (name.trim()) {
        callbacks.onDataChanged(addProject(data, name.trim()));
      }
    });
  });
  for (const project of data.projects) {
    renderProject(boardEl, project, callbacks);
  }
}
function renderProject(boardEl, project, callbacks) {
  const data = callbacks.getData();
  const projectEl = boardEl.createDiv({ cls: "kanban-project" });
  projectEl.style.borderLeftColor = project.color;
  projectEl.setAttribute("data-project-id", project.id);
  const headerEl = projectEl.createDiv({ cls: "kanban-project-header" });
  headerEl.style.backgroundColor = project.color + "20";
  const chevron = headerEl.createDiv({ cls: "kanban-chevron" });
  chevron.textContent = project.collapsed ? "\u25B6" : "\u25BC";
  chevron.addEventListener("click", () => {
    callbacks.onDataChanged(updateProject(data, project.id, { collapsed: !project.collapsed }));
  });
  const nameEl = headerEl.createDiv({ cls: "kanban-project-name", text: project.name });
  nameEl.addEventListener("click", () => {
    startInlineEdit(nameEl, project.name, (newName) => {
      if (newName.trim() && newName.trim() !== project.name) {
        callbacks.onDataChanged(updateProject(data, project.id, { name: newName.trim() }));
      }
    });
  });
  const colorSwatch = headerEl.createDiv({ cls: "kanban-color-swatch" });
  colorSwatch.style.backgroundColor = project.color;
  const colorInput = colorSwatch.createEl("input", { type: "color" });
  colorInput.value = project.color;
  colorInput.addEventListener("input", (e) => {
    const newColor = e.target.value;
    callbacks.onDataChanged(updateProject(data, project.id, { color: newColor }));
  });
  const deleteBtn = headerEl.createDiv({ cls: "kanban-delete-btn", text: "\xD7" });
  deleteBtn.setAttribute("aria-label", "Delete project");
  deleteBtn.addEventListener("click", () => {
    if (confirm(`Delete project "${project.name}" and all its columns and cards?`)) {
      callbacks.onDataChanged(removeProject(data, project.id));
    }
  });
  if (!project.collapsed) {
    const columnsEl = projectEl.createDiv({ cls: "kanban-columns" });
    for (const column of project.columns) {
      renderColumn(columnsEl, project, column, callbacks);
    }
    setupColumnDropZone(columnsEl, project.id, callbacks);
    const addColBtn = columnsEl.createDiv({ cls: "kanban-add-column" });
    const addColBtnInner = addColBtn.createEl("button", {
      cls: "kanban-add-column-btn",
      text: "+ Add Column"
    });
    addColBtnInner.addEventListener("click", () => {
      startInlineInput(addColBtnInner, "Column name...", (name) => {
        if (name.trim()) {
          callbacks.onDataChanged(addColumn(data, project.id, name.trim()));
        }
      });
    });
  }
}
function renderColumn(columnsEl, project, column, callbacks) {
  const data = callbacks.getData();
  const isDone = isDoneColumn(column);
  const columnEl = columnsEl.createDiv({ cls: "kanban-column" });
  columnEl.setAttribute("data-column-id", column.id);
  columnEl.setAttribute("data-project-id", project.id);
  const headerEl = columnEl.createDiv({ cls: "kanban-column-header" });
  if (!isDone) {
    const grip = headerEl.createDiv({ cls: "kanban-column-grip", text: "\u2801" });
    setupColumnDrag(grip, columnEl, project.id, column.id);
  }
  const nameEl = headerEl.createDiv({ cls: "kanban-column-name", text: column.name });
  if (isDone) {
    nameEl.style.cursor = "default";
  } else {
    nameEl.addEventListener("click", () => {
      startInlineEdit(nameEl, column.name, (newName) => {
        if (newName.trim() && newName.trim() !== column.name) {
          callbacks.onDataChanged(updateColumn(data, project.id, column.id, { name: newName.trim() }));
        }
      });
    });
  }
  headerEl.createDiv({ cls: "kanban-column-count", text: `${column.cards.length}` });
  if (!isDone) {
    const deleteBtn = headerEl.createDiv({ cls: "kanban-column-delete", text: "\xD7" });
    deleteBtn.setAttribute("aria-label", "Delete column");
    deleteBtn.addEventListener("click", () => {
      callbacks.onDataChanged(removeColumn(data, project.id, column.id));
    });
  }
  const cardsEl = columnEl.createDiv({ cls: "kanban-cards" });
  cardsEl.setAttribute("data-column-id", column.id);
  cardsEl.setAttribute("data-project-id", project.id);
  for (const card of column.cards) {
    renderCard(cardsEl, project, column, card, callbacks);
  }
  setupCardDropZone(cardsEl, project.id, column.id, callbacks);
  const addCardBtn = columnEl.createDiv({ cls: "kanban-add-card" });
  const addCardBtnInner = addCardBtn.createEl("button", {
    cls: "kanban-add-card-btn",
    text: "+"
  });
  addCardBtnInner.addEventListener("click", () => {
    startInlineInput(addCardBtnInner, "Card title...", (title) => {
      if (title.trim()) {
        callbacks.onDataChanged(addCard(data, project.id, column.id, title.trim()));
      }
    });
  });
}
function renderCard(cardsEl, project, column, card, callbacks) {
  const data = callbacks.getData();
  const cardEl = cardsEl.createDiv({ cls: "kanban-card" });
  cardEl.setAttribute("data-card-id", card.id);
  cardEl.setAttribute("data-column-id", column.id);
  cardEl.setAttribute("data-project-id", project.id);
  const titleEl = cardEl.createDiv({ cls: "kanban-card-title", text: card.title });
  titleEl.addEventListener("click", (e) => {
    e.stopPropagation();
    startInlineEdit(titleEl, card.title, (newTitle) => {
      if (newTitle.trim() && newTitle.trim() !== card.title) {
        callbacks.onDataChanged(updateCard(data, card.id, { title: newTitle.trim() }));
      }
    });
  });
  if (!isDoneColumn(column)) {
    const doneBtn = cardEl.createDiv({ cls: "kanban-card-done", text: "\u2713" });
    doneBtn.setAttribute("aria-label", "Move to Done");
    doneBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      const doneCol = project.columns.find((c) => isDoneColumn(c));
      if (!doneCol)
        return;
      const stripped = card.title.replace(/^\[.*?\]\s*/, "");
      const newTitle = `[${column.name}] ${stripped}`;
      let newData = updateCard(data, card.id, { title: newTitle });
      newData = moveCard(newData, card.id, project.id, doneCol.id, doneCol.cards.length);
      callbacks.onDataChanged(newData);
    });
  }
  const deleteBtn = cardEl.createDiv({ cls: "kanban-card-delete", text: "\xD7" });
  deleteBtn.addEventListener("click", (e) => {
    e.stopPropagation();
    callbacks.onDataChanged(removeCard(data, card.id));
  });
  setupCardDrag(cardEl, card.id, project.id, column.id);
}
function setupCardDropZone(cardsEl, projectId, columnId, callbacks) {
  cardsEl.addEventListener("dragover", (e) => {
    var _a;
    if (isColumnDragActive())
      return;
    if (!((_a = e.dataTransfer) == null ? void 0 : _a.types.includes("application/kanban-card")))
      return;
    e.preventDefault();
    e.dataTransfer.dropEffect = "move";
    cardsEl.querySelectorAll(".kanban-placeholder").forEach((el) => el.remove());
    const placeholder = createDiv({ cls: "kanban-placeholder" });
    const afterElement = getDragAfterElement(cardsEl, e.clientY);
    if (afterElement) {
      cardsEl.insertBefore(placeholder, afterElement);
    } else {
      cardsEl.appendChild(placeholder);
    }
  });
  cardsEl.addEventListener("dragleave", (e) => {
    if (!cardsEl.contains(e.relatedTarget)) {
      cardsEl.querySelectorAll(".kanban-placeholder").forEach((el) => el.remove());
    }
  });
  cardsEl.addEventListener("drop", (e) => {
    var _a;
    if (isColumnDragActive())
      return;
    if (!((_a = e.dataTransfer) == null ? void 0 : _a.types.includes("application/kanban-card")))
      return;
    e.preventDefault();
    e.stopPropagation();
    cardsEl.querySelectorAll(".kanban-placeholder").forEach((el) => el.remove());
    const cardData = e.dataTransfer.getData("application/kanban-card");
    if (!cardData)
      return;
    try {
      const payload = JSON.parse(cardData);
      const afterElement = getDragAfterElement(cardsEl, e.clientY);
      let targetIndex;
      if (afterElement) {
        const cards = Array.from(cardsEl.querySelectorAll(".kanban-card"));
        targetIndex = cards.indexOf(afterElement);
      } else {
        targetIndex = cardsEl.querySelectorAll(".kanban-card").length;
      }
      const data = callbacks.getData();
      const newData = moveCard(data, payload.cardId, projectId, columnId, targetIndex);
      callbacks.onDataChanged(newData);
    } catch (e2) {
    }
  });
}
function getDragAfterElement(container, y) {
  const draggableElements = Array.from(container.querySelectorAll(".kanban-card:not(.dragging)"));
  let closestElement = null;
  let closestOffset = Number.NEGATIVE_INFINITY;
  for (const child of draggableElements) {
    const box = child.getBoundingClientRect();
    const offset = y - box.top - box.height / 2;
    if (offset < 0 && offset > closestOffset) {
      closestOffset = offset;
      closestElement = child;
    }
  }
  return closestElement;
}
function startInlineEdit(el, currentValue, onSave) {
  const input = createEl("input", { type: "text", cls: "kanban-inline-input" });
  input.value = currentValue;
  const originalText = el.textContent;
  el.textContent = "";
  el.appendChild(input);
  input.focus();
  input.select();
  const finish = (save) => {
    const value = input.value;
    el.textContent = save ? value || originalText : originalText;
    if (save) {
      onSave(value);
    }
  };
  input.addEventListener("keydown", (e) => {
    if (e.key === "Enter") {
      e.preventDefault();
      finish(true);
    } else if (e.key === "Escape") {
      e.preventDefault();
      finish(false);
    }
  });
  input.addEventListener("blur", () => {
    finish(true);
  });
}
function startInlineInput(anchor, placeholder, onSave) {
  const input = createEl("input", { type: "text", cls: "kanban-inline-input", placeholder });
  const parent = anchor.parentElement;
  if (!parent)
    return;
  anchor.style.display = "none";
  parent.insertBefore(input, anchor.nextSibling);
  input.focus();
  const finish = (save) => {
    const value = input.value;
    input.remove();
    anchor.style.display = "";
    if (save && value.trim()) {
      onSave(value);
    }
  };
  input.addEventListener("keydown", (e) => {
    if (e.key === "Enter") {
      e.preventDefault();
      finish(true);
    } else if (e.key === "Escape") {
      e.preventDefault();
      finish(false);
    }
  });
  input.addEventListener("blur", () => {
    finish(true);
  });
}

// src/KanbanBoardView.ts
var VIEW_TYPE_KANBAN = "kanban-board-view";
var KanbanBoardView = class extends import_obsidian2.TextFileView {
  constructor(leaf) {
    super(leaf);
    this.boardData = createEmptyBoardData();
  }
  getViewType() {
    return VIEW_TYPE_KANBAN;
  }
  getDisplayText() {
    var _a, _b;
    return (_b = (_a = this.file) == null ? void 0 : _a.basename) != null ? _b : "Kanban Board";
  }
  getIcon() {
    return "kanban";
  }
  getViewData() {
    return serializeBoardData(this.boardData);
  }
  setViewData(data, clear) {
    const parsed = parseBoardData(data);
    if (parsed) {
      const migrated = ensureDoneColumns(parsed);
      this.boardData = migrated;
      if (migrated !== parsed) {
        this.requestSave();
      }
    } else {
      this.boardData = createEmptyBoardData();
    }
    this.refresh();
  }
  clear() {
    this.boardData = createEmptyBoardData();
  }
  refresh() {
    const container = this.contentEl;
    container.empty();
    container.addClass("kanban-board-container");
    renderBoard(container, {
      onDataChanged: (newData) => {
        this.boardData = newData;
        this.requestSave();
        this.refresh();
      },
      getData: () => this.boardData
    });
  }
};

// src/main.ts
var MultiProjectKanbanPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    this.registerView(VIEW_TYPE_KANBAN, (leaf) => new KanbanBoardView(leaf));
    this.originalSetViewState = import_obsidian3.WorkspaceLeaf.prototype.setViewState;
    const plugin = this;
    const patchedSetViewState = async function(viewState, eState) {
      var _a;
      if (viewState.type === "markdown" && ((_a = viewState.state) == null ? void 0 : _a.file)) {
        const file = plugin.app.vault.getAbstractFileByPath(viewState.state.file);
        if (file instanceof import_obsidian3.TFile && file.extension === "md") {
          try {
            const content = await plugin.app.vault.read(file);
            if (content.match(/^---\n[\s\S]*?kanban-board:\s*true[\s\S]*?\n---/)) {
              const kanbanState = {
                ...viewState,
                type: VIEW_TYPE_KANBAN
              };
              return plugin.originalSetViewState.call(this, kanbanState, eState);
            }
          } catch (e) {
          }
        }
      }
      return plugin.originalSetViewState.call(this, viewState, eState);
    };
    import_obsidian3.WorkspaceLeaf.prototype.setViewState = patchedSetViewState;
    this.addRibbonIcon("kanban", "Create new kanban board", async () => {
      await this.createNewBoard();
    });
    this.addCommand({
      id: "create-new-kanban-board",
      name: "Create new kanban board",
      callback: async () => {
        await this.createNewBoard();
      }
    });
  }
  onunload() {
    if (this.originalSetViewState) {
      import_obsidian3.WorkspaceLeaf.prototype.setViewState = this.originalSetViewState;
    }
  }
  async createNewBoard() {
    const data = createEmptyBoardData();
    const content = serializeBoardData(data);
    let filename = "Kanban Board.md";
    let counter = 1;
    while (this.app.vault.getAbstractFileByPath(filename)) {
      filename = `Kanban Board ${counter}.md`;
      counter++;
    }
    const file = await this.app.vault.create(filename, content);
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(file);
    new import_obsidian3.Notice("Created new kanban board");
  }
};
